### ISSUE TITLE
Register for Sunlight Congress API and get an API key.

### ISSUE THREAD

**Issue by gargium** [gargium/IBM-Civic-Engagement-Bot#12]

**Comment by ravikjay** [comment]
Sunlight Labs is closing down. Another group, ProPublica, is integrating Sunlight's Congress API into its own API slowly and until they do, the Sunlight Congress API can be used without a key. There's no time-frame on how long this will be. ProPublica has their own Congress API but this is limited to 5000 requests per day. Looks like we'll have to go with ProPublica long-term.

**Comment by ravikjay** [comment]
I have a ProPublica API Key.
